DROP VIEW LOGINVIEW;
CREATE VIEW LOGINVIEW AS SELECT LOGIN,PASSWORD,TYPES FROM ACCOUNT WHERE CONFIRMED=1 AND ACTIVE=1;

DELETE FROM SOP.MNOTE;
DELETE FROM SOP.ENOTE;
UPDATE SOP.ACCOUNT SET TEAM_ID_FK=null;
DELETE FROM SOP.TEAM;
DELETE FROM SOP.PERSONALDATA;
DELETE FROM SOP.ACCOUNT;

INSERT INTO SOP.ACCOUNT (ID, ACTIVE, CONFIRMED, LOGIN, PASSWORD, TYPES, VERSION) VALUES (1,1,1,'login1','10a23e7eacabe2317f458fac266a50233d5d02b31244be70477f4d780b7d2255','Admin',1);
INSERT INTO SOP.ACCOUNT (ID, ACTIVE, CONFIRMED, LOGIN, PASSWORD, TYPES, VERSION) VALUES (2,1,1,'login2','10a23e7eacabe2317f458fac266a50233d5d02b31244be70477f4d780b7d2255','Manager',1);
INSERT INTO SOP.ACCOUNT (ID, ACTIVE, CONFIRMED, LOGIN, PASSWORD, TYPES, VERSION) VALUES (3,1,1,'login3','10a23e7eacabe2317f458fac266a50233d5d02b31244be70477f4d780b7d2255','Employee',1);
INSERT INTO SOP.ACCOUNT (ID, ACTIVE, CONFIRMED, LOGIN, PASSWORD, TYPES, VERSION) VALUES (4,0,1,'login4','10a23e7eacabe2317f458fac266a50233d5d02b31244be70477f4d780b7d2255','Employee',1);
INSERT INTO SOP.ACCOUNT (ID, ACTIVE, CONFIRMED, LOGIN, PASSWORD, TYPES, VERSION) VALUES (5,1,1,'login5','10a23e7eacabe2317f458fac266a50233d5d02b31244be70477f4d780b7d2255','Manager',1);
INSERT INTO SOP.ACCOUNT (ID, ACTIVE, CONFIRMED, LOGIN, PASSWORD, TYPES, VERSION) VALUES (6,1,1,'login6','10a23e7eacabe2317f458fac266a50233d5d02b31244be70477f4d780b7d2255','Employee',1);
INSERT INTO SOP.ACCOUNT (ID, ACTIVE, CONFIRMED, LOGIN, PASSWORD, TYPES, VERSION) VALUES (7,0,1,'login7','10a23e7eacabe2317f458fac266a50233d5d02b31244be70477f4d780b7d2255','Employee',1);

INSERT INTO SOP.PERSONALDATA (ID, EMAIL, NAMED, SURNAME) VALUES (1,'rwilhelmi@xx.com','Roman','Wilhelmi');
INSERT INTO SOP.PERSONALDATA (ID, EMAIL, NAMED, SURNAME) VALUES (2,'wpokora@xx.com','Wojciech','Pokora');
INSERT INTO SOP.PERSONALDATA (ID, EMAIL, NAMED, SURNAME) VALUES (3,'wpyrkosz@xx.com','Witold','Pyrkosz');
INSERT INTO SOP.PERSONALDATA (ID, EMAIL, NAMED, SURNAME) VALUES (4,'jgajos@xx.com','Janusz','Gajos');
INSERT INTO SOP.PERSONALDATA (ID, EMAIL, NAMED, SURNAME) VALUES (5,'bdykiel@xx.com','Bożena','Dykiel');
INSERT INTO SOP.PERSONALDATA (ID, EMAIL, NAMED, SURNAME) VALUES (6,'jturek@xx.com','Jerzy','Turek');
INSERT INTO SOP.PERSONALDATA (ID, EMAIL, NAMED, SURNAME) VALUES (7,'ktkacz@xx.com','Krystyna','Tkacz');


INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (203, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2013, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2013-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 2); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (204, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2014, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2014-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 2); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (205, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2015, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2015-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 2); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (206, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2013, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2013-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 3); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (207, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2014, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2014-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 3); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (208, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2015, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2015-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 3); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (209, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2013, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2013-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 4); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (210, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2014, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2014-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 4); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (211, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2015, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2015-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 4); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (212, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2013, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2013-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 5); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (213, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2014, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2014-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 5); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (214, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2013, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2013-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 6); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (215, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2014, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2014-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 6); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (216, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2013, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2013-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 7); 
INSERT INTO SOP.ENOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMED, IMPROVEMENT, MOBILITY, NACTIVITY, NOTEYEAR, PROMISES, SAVED, TARGET, VERSION, EMPLOYEE_ID_FK) VALUES (217, 'Realizacja planu stworzenia dokumentu agregującego wszystkie czynności niezbędne do właściwego zarządzania wybraną jednostką, a wpływające na sprawne prowadzenie negocjacji z potencjalnym kontrahentem', 'Próba odnalezienia właściwej ścieżki do osiągnięcia wymaganych ustawowo elementów, posadowionych poza deklarowaną przez udziałowców wartością, a przyczyniającą się do zmiany warunków brzegowych', 1, 'poprawy wymaga metodologia wyprowadzona z historycznych założeń, a nie mająca żywego związku z aktualną sytuacją geopolityczną', 2, 'próba zaznajomienia się z zakresem obowiązków niezajmowanego w przedsiębiorstwie stanowiska', 2014, 'nie odniosłem się do proponowanych zależności, przez co skutek zespołowy nie został osiągnięty na wystarczająco wczesnym etapie pracy działu piętrowego', '2014-12-02 15:55:32.201', 'poprawa funkcjonowania abstrakcyjności zamierzeń', 2, 7); 


INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (302, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2013-12-07 15:55:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2013, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 2);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (303, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2014-12-07 15:53:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2014, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 2);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (304, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2015-12-07 15:53:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2015, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 2);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (305, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2013-12-07 15:55:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2013, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 3);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (306, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2014-12-07 15:53:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2014, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 3);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (307, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2013-12-07 15:57:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2013, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 4);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (308, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2014-12-07 15:56:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2014, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 4);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (309, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2015-12-07 15:58:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2015, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 2, 4);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (310, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2013-12-07 15:15:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2013, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 5, 5);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (311, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2014-12-07 15:25:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2014, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 5, 5);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (312, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2013-12-07 15:15:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2013, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 5, 6);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (313, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2014-12-07 15:25:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2014, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 5, 6);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (314, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2013-12-07 15:45:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2013, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 5, 7);  
INSERT INTO SOP.MNOTE (ID, ACHIEVEMENTS, ASPIRATION, CONFIRMATION, IMPROVEMENT, NACTIVITY, NOTE, NOTEA, NOTEYEAR, POTENT,PROMISES,SUMMARY,TARGET,VERSION,CONFIRM_ID,EMPLOYEE_ID_FK) VALUES (315, 'Zrealizowanie założeń programowo nadrzędnych, statutowo przyjętych do reorganizacji', 'Próba podjęcia zadania ujednolicenia zespołu ekspertów', '2014-12-07 15:55:32.201', 'Poprawa podejścia do zastanej metodologii w nieoczywisty sposób', 'Kontrola nad efektywnością impulsywności wobec niestosownych elementów', 3, 3, 2014, 2, 'zrealizowane główne postanowienia', 'pracownik wymagający opieki, ale z możliwym szybkim rozwinięciem posiadanych predyspozycji', 'objęcie założeniami i utrzymanie aktualnego zaangażowania', 1, 5, 7); 



INSERT INTO SOP.TEAM (ID, TEAM_NAME, VERSION, TEAM_MANAGER_ID_FK) VALUES (301, 'Kadry', 1, 2);
INSERT INTO SOP.TEAM (ID, TEAM_NAME, VERSION, TEAM_MANAGER_ID_FK) VALUES (302, 'Księgowość', 1, 5);
INSERT INTO SOP.TEAM (ID, TEAM_NAME, VERSION) VALUES (303, 'Sekretariat', 1);
INSERT INTO SOP.TEAM (ID, TEAM_NAME, VERSION) VALUES (304, 'Kierownictwo', 1);

UPDATE SOP.ACCOUNT SET TEAM_ID_FK=301 WHERE ACCOUNT.ID=3;
UPDATE SOP.ACCOUNT SET TEAM_ID_FK=301 WHERE ACCOUNT.ID=4;
UPDATE SOP.ACCOUNT SET TEAM_ID_FK=302 WHERE ACCOUNT.ID=6;
UPDATE SOP.ACCOUNT SET TEAM_ID_FK=302 WHERE ACCOUNT.ID=7;
